<section class="promote" itemtype="http://schema.org/ItemList">

    <div class="">
        <h1 class="head-title">Wybrane rośliny z naszej oferty:
            <a class="link-more" href="http://<?php echo Manager_Config::PDF_CATALOG; ?>">Katalog z naszą aktualną ofertą "Wiosna 2016" (wersja do druku)</a>
        
        </h1>
        <?php if ($this->list instanceof Model_Collection): ?>   
            <ul class="promote-list row index">
                <?php foreach ($this->list as $plant): ?>
                    <?php if ($plant instanceof Model_Plant_Container): ?>
                        <li class="promote-item middle-view col-xs-12 col-rs-12 col-sm-12 col-md-6 col-lg-4" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product"> 
                            <div class="promote-container">
                                <div class="plant ">
                                    <?php
                                    $this->partial('Offer/View/Partial/Plant.phtml', array('plant' => $plant,
                                        'htag' => 'h2',
                                        'dtag' => 'div',
                                        'ltag' => 'span',
                                        'vtag' => 'span'));
                                    ?>
                                    <a class="link-more" href="<?php echo $plant->getCategory()->getUrl(); ?>">zobacz pełny katalog kategorii: <b><?php echo $plant->getCategory()->getName(); ?></b></a>
                                </div>
                            </div>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>Pod podanym adresem brak wyszukania oferty w bazie. Sprawdź adres czy jest poprawny.</p>
        <?php endif; ?> 
    </div>
    <?php $this->partial('Index/View/Partial/Contact.phtml'); ?> 
</section>