<section class="promote" itemtype="http://schema.org/ItemList">

    
        <h1 class="head-title">Wybrane promocyjne sadzonki z naszej oferty:            
        <?php $this->partial('Offer/View/Partial/Pdf.phtml', array());?>
        </h1>
    <br> 
        <?php if ($this->list instanceof Model_Collection): ?>   
            <ul class="promote-list row index">
                <?php foreach ($this->list as $plant): ?>
                    <?php if ($plant instanceof Model_Plant_Container): ?>
                        <li class="promote-item middle-view col-xs-12 col-rs-12 col-sm-12 col-md-6 col-lg-4" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product"> 
                            <div class="promote-container">
                                <div class="plant ">
                                    <?php
                                    $this->partial('Offer/View/Partial/Plant.phtml', array('plant' => $plant,
                                        'htag' => 'h2',
                                        'dtag' => 'div',
                                        'ltag' => 'span',
                                        'vtag' => 'span'));
                                    ?>
                                    <a class="link-more" href="<?php echo $plant->getCategory()->getUrl(); ?>">zobacz: <b><?php echo $plant->getCategory()->getName(); ?></b></a>
                                </div>
                            </div>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                        <li class="promote-item middle-view col-xs-12 col-rs-12 col-sm-12 col-md-6 col-lg-4">
                                <div class="promote-container">
                                    <div class="promote-info">
                                        <p class="p-text"> 
                                            <br>
                                            W chwili obecnej nie wszystkie rośliny dostępne w naszym <a href="/kontakt">Punkcie Sprzedaży</a> są obecne w katalogu firmowym.<br><br>
                                            Pełną ofertę możemy przesłać mailowo lub przekazać telefonicznie. <br><br>
                                            <b>Zapraszamy Państwa do naszego Punktu Sprzedaży oraz do zapoznania się z poniższym katalogiem:</b>
                                            <br><br>
                                            <?php $this->partial('Offer/View/Partial/Pdf.phtml', array()); ?>
                                        </p>
                                    </div>
                                </div>
                            </li>
            </ul>
    
        
        <?php $this->partial('Common/View/Partial/Pagination.phtml', array('list' => $this->list, 'url' => '/'));?>
        <?php else: ?>
            <?php $this->partial('Offer/View/Partial/Empty.phtml', array());?>
        <?php endif; ?> 
    
    <?php $this->partial('Index/View/Partial/Contact.phtml'); ?> 
</section>
<?php $this->ob(); ?>
<script src="/js/mig/mig.image.responsive.js"></script>
<script type="text/javascript">
// <![CDATA[
    mig.image.responsive(window, {screen: <?php echo Manager_Config_Js::SCREEN_MD_MIN; ?> });
// ]]>
</script>
<?php $this->clean(); ?>