<section itemscope itemtype="http://data-vocabulary.org/Review" class="row review company">   
        <!-- <span itemprop="rating" class="hide">5</span> img-fluid-->
    <div class="review-photo-1 img-fluid">
        <div class="review-about gradient">
            <time itemprop="dtreviewed" datetime="2016-04-02">2 kwietnia,</time>
            <span itemprop="reviewer">"Mirage" o swojej działalności:</span>
        </div>
    </div>
    <div class="review-text row">
        <div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-9">
            <h2 itemprop="itemreviewed" class="head-title review-title">Szkółka ogrodnicza</h2>
            <p itemprop="description" class="p-text review-description">Zajmujemy się produkcją i sprzedażą drzew i krzewów ozdobnych oraz innych roślin.</p>
        </div>
    </div>
    <div class="review-photo-2 img-fluid">
        <div class="review-about gradient">                
            <span>W naszym ogrodzie znajdziesz: </span>
        </div>
    </div>
    <div class="review-text row">
        <div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-9">
            <h3 class="head-title review-title">Oferujemy w sprzedaży:</h3>
            <p itemprop="summary" class="p-text review-description">Wysokiej jakości drzewa i krzewy iglaste, liściaste, szczepione, wrzosowe, byliny oraz rośliny jednoroczne.</p>
        </div>
    </div>
    <div class="review-photo-3 img-fluid">
        <div class="review-about gradient">                
            <a class="review-link" href="http://<?php echo Manager_Config::PDF_CATALOG; ?>">Katalog z naszą aktualną ofertą "Wiosna 2016" (wersja do druku)</a>
        </div>
    </div>

    <?php $this->partial('Index/View/Partial/Contact.phtml'); ?>

</section>