<div itemscope itemtype="http://schema.org/Organization" class="contact"> 
    <?php $this->render('Contact/View/Partial/Company.phtml'); ?>
    <p class="p-text contact-text-label">Dane kontaktowe:</p>
    <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <?php $this->render('Contact/View/Partial/Address.phtml'); ?>
    </div>
    <div itemprop="location"> 
        <?php $this->render('Contact/View/Partial/Geolocation.phtml'); ?>        
    </div>
    <div class="text-center">
        <?php $this->partial('Contact/View/Partial/Logo.phtml', array('showDomain' => true)); ?> 
    </div>
</div>
