<br>
<p class="p-text"> Przepraszam, wkrótce i ten typ roślin będzie dostępny w naszym firmowym katalogu. <br><br>
    W chwili obecnej rośliny z tej kategorii <b>są dostępne w naszym <a href="/kontakt">punkcie sprzedaży</a> w ilości detalicznej</b>, ofertę możemy też przesłać mailowo lub przekazać telefonicznie. 
    Zapraszamy Państwa do naszego Punktu Sprzedaży oraz do zapoznania się z  poniższym katalogiem:<br><br>
<?php $this->partial('Offer/View/Partial/Pdf.phtml', array()); ?>

</p>
<br>