<div class="header-brand"><span class="hide">Ogrodnictwo i Sadownictwo.</span></div>
<div class="header-domain"><span class="hide">sadzonka.eu</span></div>
<h2 class="header-text">Szkółka ogrodnicza</h2>
<span class="hide sadzonki">Sadzonki ogrodowe</span>
<div class="header-brand-img">    
    <img src="/svg/logo-mirage-piwonia-base.svg" alt="logo: Mirage - szkółka ogrodnicza" class="header-logo">        
</div>
