<div class="footer-body">
    <p class="footer-text copyright">Copyright (c) <?php echo date('Y'); ?> sadzonka.eu, Szkółka ogrodnicza "Mirage" - Wszelkie prawa zastrzeżone.</p>
    <a href="/polityka-cookie/" class="footer-link">O Polityce Plików Cookies.</a>
</div>
<?php $this->ob();?>
<script src="/js/mig/mig.cookie.policy.js"></script>
<script type="text/javascript">
// <![CDATA[
mig.cookie.policy(window, {});
// ]]>
</script>
<?php $this->clean();?>