<div class="row">
    <form class="form-inline col-md-11 col-md-offset-1">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="id, nazwa">
            <button type="submit" class="btn btn-default">Filtruj</button>
        </div>

        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
</div>
<br>
<br>
<div class="row">
    <div class="col-xs-2">
        <?php $this->partial('formsan/view/partial/list.phtml', array()); ?>
    </div>

    <div class="col-xs-10">
        <?php $this->partial('formsan/view/partial/form.phtml', array()); ?>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>