<section class="offer" itemtype="http://schema.org/ItemList">

    <div class="offer-head">
        <h1 class="head-title">Oferta firmy <span itemprop="manufacturer">"Mirage"</span>: <?php if ($this->product): ?><span itemprop="brand"><?php echo $this->product->getTitle(); ?>
            </span><?php endif; ?></h1>
<?php $this->partial('Offer/View/Partial/Pdf.phtml', array()); ?>
        <?php $this->partial('Offer/View/Partial/Switch.phtml', array()); ?>
        

        <?php if ($this->list instanceof Model_Collection): ?>   
            <ul class="offer-list">
                <?php foreach ($this->list as $category): ?>
                    <h3 class="offer-list-title"><a class="offer-list-title-link" href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?></a> (<?php echo $category->getItems()->getSummaryItems(); ?>)</h3>
                    <h5 class="s-text">Wybrane z oferty:</h5>
                    <?php foreach ($category->getItems() as $plant): ?>
                        <?php if ($plant instanceof Model_Plant_Container): ?>
                            <li class="offer-item plant big-view" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product"> 
                                <?php
                                $this->partial('Offer/View/Partial/Plant.phtml', array('plant' => $plant,
                                    'htag' => 'h2',
                                    'dtag' => 'div',
                                    'ltag' => 'span',
                                    'vtag' => 'span'));
                                ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <div class="category row">
                        <div class="category-icon col-xs-12 col-sm-6">
                            <img class="category-img img-responsive" src="//<?php echo $category->getIcon(); ?>" alt="<?php echo $category->getName(); ?>">  
                        </div>                        
                        <p class="category-desc s-text col-xs-12 col-sm-6"><?php echo $category->getDescription(); ?></p>
                        <a class="link-more" href="<?php echo $category->getUrl(); ?>">zobacz: <b><?php echo $category->getName(); ?></b></a>

                    </div>    
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <?php $this->partial('Offer/View/Partial/Empty.phtml', array());?>
        <?php endif; ?>      

    </div>
</section>
<?php $this->ob(); ?>
<script src="/js/mig/mig.image.responsive.js"></script>
<script type="text/javascript">
// <![CDATA[
    mig.image.responsive(window, {screen: <?php echo Manager_Config_Js::SCREEN_MD_MIN; ?> });
// ]]>
</script>
<?php $this->clean(); ?>
