<section class="offer" itemtype="http://schema.org/ItemList">

    <div class="offer-head">

        <?php if ($this->list instanceof Model_Collection): ?> 
            <h1 class="head-title">Oferta firmy <span itemprop="manufacturer">"Mirage"</span>: 
                <?php /* if ($this->product): ?><span itemprop="brand"><?php echo $this->product->getTitle(); ?></span><?php endif; */ ?>
                <span itemprop="brand"><?php echo $this->list->current()->getCategory()->getName(); ?></span>
            </h1>
            <?php $this->partial('Offer/View/Partial/Pdf.phtml', array()); ?>
            <?php $this->partial('Offer/View/Partial/Switch.phtml', array()); ?>


            <ul class="offer-list">
                <?php foreach ($this->list as $plant): ?>
                    <?php if ($plant instanceof Model_Plant_Container): ?>
                        <li class="offer-item plant big-view" itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product"> 
                            <?php
                            $this->partial('Offer/View/Partial/Plant.phtml', array('plant' => $plant,
                                'htag' => 'h2',
                                'dtag' => 'div',
                                'ltag' => 'span',
                                'vtag' => 'span'));
                            ?>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>        
        <?php $this->partial('Common/View/Partial/Pagination.phtml', array('list' => $this->list, 'url' => $plant->getCategory()->getUrl()));?>

        <?php else: ?>
        <?php $this->partial('Offer/View/Partial/Empty.phtml', array());?>
        <?php endif; ?>


    </div>
</section>
<?php $this->ob(); ?>
<script src="/js/mig/mig.image.responsive.js"></script>
<script type="text/javascript">
// <![CDATA[
    mig.image.responsive(window, {screen: <?php echo Manager_Config_Js::SCREEN_MD_MIN; ?>});
// ]]>
</script>
<?php $this->clean(); ?>