<div itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product">
    <div class="offer-head">
        <h3 class="head-title">Oferta firmy <span itemprop="manufacturer">"Mirage"</span>:
        <span itemprop="brand"><?php echo $this->plant->getCategory()->getName(); ?></span>
        </h3>
    </div>
    <section class="plant large-view">
        
        <?php if ($this->plant instanceof Model_Plant_Container): ?>
            <?php
            $this->partial('Offer/View/Partial/Plant.phtml', array('plant' => $this->plant,
                'htag' => 'h1',
                'dtag' => 'dl',
                'ltag' => 'dt',
                'vtag' => 'dd'));
            ?>
        <?php endif; ?>
             <a class="link-more" href="<?php echo $this->plant->getCategory()->getUrl(); ?>">zobacz: <b><?php echo $this->plant->getCategory()->getName(); ?></b></a>
    
            <?php $this->partial('Offer/View/Partial/Pdf.phtml', array()); ?>
        
   </section>
</div>
<?php $this->ob(); ?>
<script src="/js/mig/mig.image.responsive.js"></script>
<script type="text/javascript">
// <![CDATA[
    mig.image.responsive(window, {screen: <?php echo Manager_Config_Js::SCREEN_MD_MIN; ?> });
// ]]>
</script>
<?php $this->clean(); ?>