<span class="p-text contact-text-label">E-mail: </span><span itemprop="email" class="p-text contact-text"><a href="mailto:biuro@sadzonka.eu">biuro@sadzonka.eu</a></span><br>
<span class="p-text contact-text-label">Telefon: </span><span itemprop="telephone" class="p-text contact-text"><b>519 431 929</b>, 506 455 392</span><br>                    
<span class="p-text contact-text-label">Adres Punktu Sprzedaży: </span><br>
<span itemprop="streetAddress" class="p-text contact-text">Siercza 485</span><br>
<span itemprop="postalCode" class="p-text contact-text">32-020</span>  -
<span itemprop="addressLocality" class="p-text contact-text">Wieliczka</span>
<br>
<span class="p-text contact-text-label">Adres Siedziby: </span><br>
<span itemprop="streetAddress" class="p-text contact-text">Pawlikowice 182</span><br>
<span itemprop="postalCode" class="p-text contact-text">32-020</span>  -
<span itemprop="addressLocality" class="p-text contact-text">Wieliczka</span>
<br>
<span itemprop="addressRegion" class="p-text contact-text">Małopolska</span>
<span itemprop="addressCountry" class="p-text contact-text">Polska.</span>