<span itemprop="name" class="p-text contact-text">Mirage</span>  -
<span itemprop="brand" class="p-text contact-text">szkółka ogrodnicza</span><br>
<span class="p-text contact-text-label">Godziny otwarcia: </span><br>
<span itemprop="openingHours"  datetime="Mon,Sat 8:00-20:00" class="p-text contact-text"><b>od poniedziałku do piątku <br> w godzinach 9:00 - 18:00, <br>w soboty 8:00 - 15:00</b></span>  
