<span class="p-text contact-text-label">Geolokalizacja:</span><br>
<span itemscope itemtype="http://schema.org/Place">
    <span itemprop="geo">        
        <span itemprop="streetAddress" class="p-text contact-text">Siercza 485</span><br>
        <span itemscope itemtype="http://schema.org/GeoCoordinates">
            <span class="p-text contact-text"> y: </span><span property="latitude" content="49.976750" class="p-text contact-text">49.976750,</span>
            <span class="p-text contact-text"> x:</span> <span property="longitude" content="20.049963" class="p-text contact-text">20.049963</span>
        </span>        
        <span itemprop="streetAddress" class="p-text contact-text">Pawlikowice 182</span><br>
        <span itemscope itemtype="http://schema.org/GeoCoordinates">
            <span class="p-text contact-text"> y: </span><span property="latitude" content="49.966016" class="p-text contact-text">49.966016,</span>
            <span class="p-text contact-text"> x:</span> <span property="longitude" content="20.054213" class="p-text contact-text">20.054213</span>
        </span>
    </span>
</span>