<section class="gallery container-fluid"> 
    <div class="bit-white"> 
        <div class="gallery-head">
            <h2 class="head-title review-title">Galeria kwiatów.</h2>
            <p class="p-text review-description">W wolnej chwili w długie zimowe wieczory oddajmy się marzeniom o ogrodzie. </p>
        </div>
    </div>
    <ul class="gallery-list row">
        <?php foreach ($this->list as $src): ?>
            <li class="gallery-item col-xs-12 col-sm-6 col-md-4 col-lg-3 clear-xs-1 clear-rs-1 clear-sm-2 clear-md-3 clear-lg-4">
                <div class="gallery-thumb">
                    <img class="gallery-img" src="<?php echo Manager_Config::iphotUrl() . $this->path; ?><?php echo $src; ?>"/>
                </div>
            </li> 
        <?php endforeach; ?>
    </ul>
    <div class="review-text"> 
        <div class="gallery-head">            
            <p class="p-text review-description">... więcej w natępnej wolnej chwili... </p>
            <p class="s-text">(Copyright (c) <?php echo date('Y');?> autor: Rena.Sonko - Wszelkie prawa zastrzeżone.)</p>
        </div>
    </div>
</section>
<a class="up-to-up" href="#">do góry</a>